name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Moin, dieser code ist unvollständing und wie eine Trainingspuppe für mich' first issue"
        pr-message: "die Spielregeln sind noch unvollständig' first pull request"
